//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eventManagementEntities : DbContext
    {
        public eventManagementEntities()
            : base("name=eventManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<decorationPlans> decorationPlans { get; set; }
        public virtual DbSet<events> events { get; set; }
        public virtual DbSet<eventType> eventType { get; set; }
        public virtual DbSet<foodItems> foodItems { get; set; }
        public virtual DbSet<foodOrders> foodOrders { get; set; }
    }
}
