//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public events()
        {
            this.foodOrders = new HashSet<foodOrders>();
        }
    
        public int eid { get; set; }
        public string etype { get; set; }
        public string edate { get; set; }
        public Nullable<int> gathering { get; set; }
        public Nullable<int> did { get; set; }
        public Nullable<int> d_price { get; set; }
        public Nullable<int> f_price { get; set; }
        public Nullable<int> total { get; set; }
    
        public virtual decorationPlans decorationPlans { get; set; }
        public virtual eventType eventType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<foodOrders> foodOrders { get; set; }
    }
}
