//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class foodOrders
    {
        public int fo_id { get; set; }
        public int eid { get; set; }
        public int fid { get; set; }
        public int qty { get; set; }
    
        public virtual events events { get; set; }
    }
}
